# Generated by Django 4.2.27 on 2026-01-26 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blocklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '黑名单',
                'db_table': 'security_blocklist',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Datacenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='机房名称')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='位置/楼层')),
            ],
            options={
                'verbose_name': '机房',
                'db_table': 'dcim_datacenter',
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('ip_address', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '登录审计',
                'db_table': 'security_login_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NetworkSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='区域名称')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='描述')),
                ('color_theme', models.CharField(default='blue', max_length=50, verbose_name='UI颜色主题')),
            ],
            options={
                'verbose_name': '业务区域',
                'db_table': 'ipam_section',
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='例: A03', max_length=50, verbose_name='机柜编号')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='机柜名称')),
                ('height', models.IntegerField(default=42, verbose_name='高度(U)')),
                ('power_limit', models.IntegerField(default=0, help_text='0表示不限制', verbose_name='额定功率(W)')),
                ('description', models.TextField(blank=True, verbose_name='备注')),
                ('datacenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='ipam.datacenter', verbose_name='所属机房')),
            ],
            options={
                'verbose_name': '机柜',
                'db_table': 'dcim_rack',
            },
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='网段名称')),
                ('cidr', models.CharField(max_length=50, unique=True, verbose_name='CIDR')),
                ('circuit_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='电路编号')),
                ('isp', models.CharField(choices=[('CT', '中国电信 (China Telecom)'), ('CM', '中国移动 (China Mobile)'), ('CU', '中国联通 (China Unicom)'), ('BN', '中国广电 (Broadnet)'), ('GOV', '政务外网统筹线路'), ('CMD', '应急指挥专网'), ('LAN', '自建光纤 / 内部局域网')], default='LAN', max_length=50, verbose_name='运营商')),
                ('bandwidth', models.CharField(blank=True, max_length=50, verbose_name='带宽容量')),
                ('vlan_id', models.IntegerField(blank=True, null=True, verbose_name='VLAN ID')),
                ('gateway', models.GenericIPAddressField(blank=True, null=True, verbose_name='网关地址')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='部署位置')),
                ('function_usage', models.CharField(blank=True, max_length=100, verbose_name='主要用途')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subnets', to='ipam.networksection')),
            ],
            options={
                'verbose_name': '网段/电路',
                'db_table': 'ipam_subnet',
            },
        ),
        migrations.CreateModel(
            name='RackDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('position', models.IntegerField(help_text='设备底座所在的U位', verbose_name='起始U位')),
                ('u_height', models.IntegerField(default=1, verbose_name='占用高度(U)')),
                ('device_type', models.CharField(choices=[('server', '服务器'), ('switch_core', '核心交换机'), ('firewall', '防火墙'), ('sandbox', '沙箱'), ('odf', 'ODF配线架'), ('ups', 'UPS电源'), ('passive', '无源设备'), ('router', '路由器'), ('other', '其他')], default='server', max_length=50, verbose_name='设备类型')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='品牌')),
                ('mgmt_ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='管理IP')),
                ('project', models.CharField(blank=True, max_length=100, verbose_name='项目名称')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='联系人')),
                ('power_usage', models.IntegerField(blank=True, default=0, null=True, verbose_name='额定功率(W)')),
                ('specs', models.TextField(blank=True, verbose_name='配置信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='ipam.rack')),
            ],
            options={
                'verbose_name': '机架设备',
                'db_table': 'dcim_rack_device',
            },
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP地址')),
                ('status', models.CharField(choices=[('online', '在线 / 正常'), ('offline', '离线 / 空闲'), ('rogue', '异常 / 私接'), ('reserved', '保留地址')], default='offline', max_length=20, verbose_name='状态')),
                ('device_name', models.CharField(blank=True, max_length=100, verbose_name='设备名称')),
                ('device_type', models.CharField(blank=True, max_length=50, verbose_name='设备类型')),
                ('owner', models.CharField(blank=True, max_length=100, verbose_name='负责人/部门')),
                ('description', models.TextField(blank=True, verbose_name='备注')),
                ('last_online', models.DateTimeField(blank=True, null=True, verbose_name='最后在线时间')),
                ('subnet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ips', to='ipam.subnet')),
            ],
            options={
                'verbose_name': 'IP资产',
                'db_table': 'ipam_ip_address',
                'ordering': ['ip_address'],
            },
        ),
    ]
