# Generated by Django 4.2.27 on 2026-01-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacenter',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='值班电话'),
        ),
        migrations.AddField(
            model_name='rackdevice',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=100, verbose_name='固定资产编号'),
        ),
        migrations.AddField(
            model_name='rackdevice',
            name='os_version',
            field=models.CharField(blank=True, max_length=100, verbose_name='操作系统'),
        ),
        migrations.AddField(
            model_name='rackdevice',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='采购日期'),
        ),
        migrations.AddField(
            model_name='rackdevice',
            name='sn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='序列号 (S/N)'),
        ),
        migrations.AddField(
            model_name='rackdevice',
            name='status',
            field=models.CharField(default='active', max_length=50, verbose_name='设备状态'),
        ),
        migrations.AddField(
            model_name='rackdevice',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, verbose_name='供应商'),
        ),
        migrations.AddField(
            model_name='rackdevice',
            name='warranty_date',
            field=models.DateField(blank=True, null=True, verbose_name='维保到期日'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='status',
            field=models.CharField(default='offline', max_length=50, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='code',
            field=models.CharField(max_length=50, verbose_name='机柜编号'),
        ),
        migrations.AlterField(
            model_name='rackdevice',
            name='device_type',
            field=models.CharField(default='server', max_length=50, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='rackdevice',
            name='position',
            field=models.IntegerField(verbose_name='起始U位'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='isp',
            field=models.CharField(blank=True, default='自建光纤', max_length=50, verbose_name='运营商'),
        ),
    ]
