# Generated by Django 4.2.27 on 2026-01-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0002_datacenter_contact_phone_rackdevice_asset_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='nat_ip',
            field=models.GenericIPAddressField(blank=True, help_text='公网IP或映射后的IP', null=True, verbose_name='映射地址'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='nat_port',
            field=models.CharField(blank=True, help_text='如: 80->8080', max_length=50, verbose_name='端口映射'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='nat_type',
            field=models.CharField(choices=[('none', '无'), ('dnat', 'DNAT (公网映射入)'), ('snat', 'SNAT (内网映射出)')], default='none', max_length=20, verbose_name='NAT类型'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='power_limit',
            field=models.IntegerField(default=0, verbose_name='额定功率(W)'),
        ),
    ]
