# Generated by Django 6.0.3 on 2026-04-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0008_datacenter_change_request_and_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blocklist',
            options={'ordering': ['-created_at'], 'verbose_name': '黑名单', 'verbose_name_plural': '黑名单'},
        ),
        migrations.AlterModelOptions(
            name='datacenter',
            options={'verbose_name': '机房', 'verbose_name_plural': '机房'},
        ),
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'ordering': ['ip_address'], 'verbose_name': 'IP 资产', 'verbose_name_plural': 'IP 资产'},
        ),
        migrations.AlterModelOptions(
            name='loginlog',
            options={'ordering': ['-timestamp'], 'verbose_name': '登录审计', 'verbose_name_plural': '登录审计'},
        ),
        migrations.AlterModelOptions(
            name='networksection',
            options={'verbose_name': '业务区域', 'verbose_name_plural': '业务区域'},
        ),
        migrations.AlterModelOptions(
            name='rack',
            options={'verbose_name': '机柜', 'verbose_name_plural': '机柜'},
        ),
        migrations.AlterModelOptions(
            name='rackdevice',
            options={'verbose_name': '机柜设备', 'verbose_name_plural': '机柜设备'},
        ),
        migrations.AlterModelOptions(
            name='subnet',
            options={'verbose_name': '网段 / 专线', 'verbose_name_plural': '网段 / 专线'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户档案', 'verbose_name_plural': '用户档案'},
        ),
        migrations.AlterField(
            model_name='datacenter',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='位置 / 楼层'),
        ),
        migrations.AlterField(
            model_name='datacenterchangeitem',
            name='network_role',
            field=models.CharField(choices=[('none', '无需网络'), ('command', '指挥网'), ('government', '政务外网'), ('other', '其他'), ('management', '指挥网（旧值兼容）'), ('service', '政务外网（旧值兼容）'), ('dual', '双网（旧值兼容）')], default='none', max_length=20, verbose_name='网络需求'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True, verbose_name='IP 地址'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='nat_ip',
            field=models.GenericIPAddressField(blank=True, help_text='公网 IP 或映射后的 IP', null=True, verbose_name='映射地址'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='nat_port',
            field=models.CharField(blank=True, help_text='例如：80 -> 8080', max_length=50, verbose_name='端口映射'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='nat_type',
            field=models.CharField(choices=[('none', '无'), ('dnat', 'DNAT (公网映射入站)'), ('snat', 'SNAT (内网映射出站)')], default='none', max_length=20, verbose_name='NAT 类型'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='owner',
            field=models.CharField(blank=True, max_length=100, verbose_name='负责人 / 部门'),
        ),
        migrations.AlterField(
            model_name='networksection',
            name='color_theme',
            field=models.CharField(default='blue', max_length=50, verbose_name='界面主题色'),
        ),
        migrations.AlterField(
            model_name='networksection',
            name='name',
            field=models.CharField(max_length=100, verbose_name='业务区域名称'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='height',
            field=models.IntegerField(default=42, verbose_name='高度 (U)'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='power_limit',
            field=models.IntegerField(default=0, verbose_name='额定功率 (W)'),
        ),
        migrations.AlterField(
            model_name='rackdevice',
            name='contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='rackdevice',
            name='mgmt_ip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='管理 IP'),
        ),
        migrations.AlterField(
            model_name='rackdevice',
            name='os_version',
            field=models.CharField(blank=True, max_length=100, verbose_name='操作系统 / 固件'),
        ),
        migrations.AlterField(
            model_name='rackdevice',
            name='position',
            field=models.IntegerField(verbose_name='起始 U 位'),
        ),
        migrations.AlterField(
            model_name='rackdevice',
            name='power_usage',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='额定功率 (W)'),
        ),
        migrations.AlterField(
            model_name='rackdevice',
            name='u_height',
            field=models.IntegerField(default=1, verbose_name='占用高度 (U)'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='function_usage',
            field=models.CharField(blank=True, max_length=100, verbose_name='核心用途'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='物理位置'),
        ),
    ]
