# Generated by Django 6.0.3 on 2026-06-22 09:30

import django.db.models.deletion
import ipam.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0014_structured_asset_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='名称')),
                ('credential_type', models.CharField(choices=[('ssh', 'SSH'), ('database', '数据库'), ('web', 'Web 后台'), ('api_key', 'API Key'), ('device', '设备账号'), ('other', '其他')], default='ssh', max_length=24, verbose_name='凭据类型')),
                ('target_type', models.CharField(choices=[('datacenter', '机房'), ('rack', '机柜'), ('device', '设备'), ('ip', 'IP 地址'), ('general', '通用')], default='general', max_length=24, verbose_name='关联对象类型')),
                ('username_hint', models.CharField(blank=True, max_length=160, verbose_name='账号提示')),
                ('vault_path', models.CharField(default=ipam.models.generate_secret_vault_path, editable=False, max_length=255, unique=True, verbose_name='OpenBao 路径')),
                ('owner_team', models.CharField(blank=True, max_length=120, verbose_name='责任团队')),
                ('environment', models.CharField(choices=[('production', '生产'), ('test', '测试'), ('development', '开发'), ('other', '其他')], default='production', max_length=24, verbose_name='环境')),
                ('sensitivity', models.CharField(choices=[('internal', '内部'), ('confidential', '机密'), ('restricted', '严格受限')], default='confidential', max_length=24, verbose_name='敏感级别')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='凭据到期时间')),
                ('rotation_days', models.PositiveIntegerField(default=90, verbose_name='轮换周期（天）')),
                ('last_rotated_at', models.DateTimeField(blank=True, null=True, verbose_name='最近轮换时间')),
                ('status', models.CharField(choices=[('active', '有效'), ('disabled', '停用')], default='active', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_secret_records', to=settings.AUTH_USER_MODEL)),
                ('datacenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secret_records', to='ipam.datacenter')),
                ('ip_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secret_records', to='ipam.ipaddress')),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secret_records', to='ipam.rack')),
                ('rack_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secret_records', to='ipam.rackdevice')),
            ],
            options={
                'verbose_name': '密码台账',
                'verbose_name_plural': '密码台账',
                'db_table': 'security_secret_record',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SecretAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_name', models.CharField(blank=True, max_length=160, verbose_name='密码条目名称')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('request', '申请'), ('approve', '批准'), ('reject', '驳回'), ('reveal', '查看'), ('rotate', '轮换')], max_length=20, verbose_name='动作')),
                ('result', models.CharField(choices=[('success', '成功'), ('denied', '拒绝'), ('error', '错误')], default='success', max_length=20, verbose_name='结果')),
                ('reason', models.TextField(blank=True, verbose_name='原因 / 说明')),
                ('ip_address', models.CharField(blank=True, max_length=64, verbose_name='来源 IP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secret_audit_events', to=settings.AUTH_USER_MODEL)),
                ('secret', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='ipam.secretrecord')),
            ],
            options={
                'verbose_name': '密码审计',
                'verbose_name_plural': '密码审计',
                'db_table': 'security_secret_audit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecretAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='取用原因')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已驳回'), ('used', '已使用'), ('expired', '已过期')], default='pending', max_length=20, verbose_name='状态')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('review_comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('approved_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='授权到期时间')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_access_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_secret_access_requests', to=settings.AUTH_USER_MODEL)),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='ipam.secretrecord')),
            ],
            options={
                'verbose_name': '密码取用申请',
                'verbose_name_plural': '密码取用申请',
                'db_table': 'security_secret_access_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
