# Generated by Django 6.0.3 on 2026-07-04 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0015_secretrecord_secretauditevent_secretaccessrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigBackupTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='备份目标名称')),
                ('management_ip', models.GenericIPAddressField(unique=True, verbose_name='管理 IP')),
                ('device_type', models.CharField(choices=[('switch', '交换机'), ('router', '路由器'), ('firewall', '防火墙'), ('other', '其他')], default='switch', max_length=32, verbose_name='设备类型')),
                ('command_profile', models.CharField(choices=[('huawei_vrp', '华为 / H3C VRP'), ('generic_show_run', '通用 show running-config')], default='huawei_vrp', max_length=32, verbose_name='命令模板')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用备份')),
                ('retention_count', models.PositiveSmallIntegerField(default=12, verbose_name='保留版本数')),
                ('schedule_label', models.CharField(blank=True, default='每周日凌晨', max_length=120, verbose_name='计划说明')),
                ('last_status', models.CharField(choices=[('not_run', '未执行'), ('success', '成功'), ('failed', '失败'), ('running', '执行中'), ('disabled', '已停用')], default='not_run', max_length=20, verbose_name='最近状态')),
                ('last_error', models.TextField(blank=True, verbose_name='最近失败原因')),
                ('last_backup_at', models.DateTimeField(blank=True, null=True, verbose_name='最近备份时间')),
                ('last_duration_seconds', models.PositiveIntegerField(default=0, verbose_name='最近耗时（秒）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_config_backup_targets', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_backup_targets', to='ipam.secretrecord', verbose_name='登录凭据')),
                ('ip_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_backup_targets', to='ipam.ipaddress', verbose_name='关联 IP 资产')),
                ('rack_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_backup_targets', to='ipam.rackdevice', verbose_name='关联机柜设备')),
            ],
            options={
                'verbose_name': '配置备份目标',
                'verbose_name_plural': '配置备份目标',
                'db_table': 'ops_config_backup_target',
                'ordering': ['management_ip', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConfigBackupVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], default='success', max_length=20, verbose_name='状态')),
                ('filename', models.CharField(blank=True, max_length=255, verbose_name='文件名')),
                ('relative_path', models.CharField(blank=True, max_length=500, verbose_name='相对路径')),
                ('bytes', models.PositiveIntegerField(default=0, verbose_name='文件大小')),
                ('sha256', models.CharField(blank=True, max_length=64, verbose_name='SHA256')),
                ('started_at', models.DateTimeField(verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='耗时（秒）')),
                ('command_profile', models.CharField(blank=True, max_length=32, verbose_name='命令模板')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ipam.configbackuptarget', verbose_name='备份目标')),
            ],
            options={
                'verbose_name': '配置备份版本',
                'verbose_name_plural': '配置备份版本',
                'db_table': 'ops_config_backup_version',
                'ordering': ['-started_at', '-id'],
            },
        ),
    ]
