# Generated by Django 6.0.3 on 2026-07-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0016_configbackuptarget_configbackupversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configbackuptarget',
            name='save_before_backup',
            field=models.BooleanField(default=True, verbose_name='采集前保存配置'),
        ),
        migrations.AddField(
            model_name='configbackuptarget',
            name='ssh_port',
            field=models.PositiveSmallIntegerField(default=22, verbose_name='SSH 端口'),
        ),
        migrations.AddField(
            model_name='configbackuptarget',
            name='timeout_seconds',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='连接超时（秒）'),
        ),
        migrations.AlterField(
            model_name='configbackuptarget',
            name='command_profile',
            field=models.CharField(choices=[('huawei_vrp', '华为 / H3C VRP'), ('h3c_comware', 'H3C Comware'), ('cisco_ios', 'Cisco IOS'), ('generic_show_run', '通用 show running-config')], default='huawei_vrp', max_length=32, verbose_name='命令模板'),
        ),
    ]
