# Generated by Django 6.0.3 on 2026-07-05 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0017_configbackuptarget_save_before_backup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigBackupPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='启用计划')),
                ('schedule_frequency', models.CharField(choices=[('manual', '手动执行'), ('daily', '每天'), ('weekly', '每周')], default='weekly', max_length=20, verbose_name='执行频率')),
                ('schedule_time', models.TimeField(default=datetime.time(3, 0), verbose_name='执行时间')),
                ('schedule_weekday', models.PositiveSmallIntegerField(default=6, verbose_name='每周星期')),
                ('execution_strategy', models.CharField(choices=[('all', '全部启用目标'), ('failed', '只执行失败设备'), ('device_type', '按设备类型'), ('datacenter', '按机房')], default='all', max_length=32, verbose_name='执行策略')),
                ('strategy_device_type', models.CharField(blank=True, default='', max_length=32, verbose_name='策略设备类型')),
                ('strategy_datacenter', models.CharField(blank=True, default='', max_length=120, verbose_name='策略机房')),
                ('retention_count', models.PositiveSmallIntegerField(default=12, verbose_name='默认保留版本数')),
                ('email_enabled', models.BooleanField(default=False, verbose_name='启用邮件通知')),
                ('email_recipients', models.TextField(blank=True, default='', verbose_name='收件人')),
                ('notify_on_success', models.BooleanField(default=False, verbose_name='成功时通知')),
                ('notify_on_failure', models.BooleanField(default=True, verbose_name='失败时通知')),
                ('email_subject_prefix', models.CharField(default='[IPAM 配置备份]', max_length=120, verbose_name='邮件主题前缀')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='最近计划执行时间')),
                ('last_run_status', models.CharField(choices=[('not_run', '未执行'), ('success', '成功'), ('failed', '失败'), ('partial', '部分失败')], default='not_run', max_length=20, verbose_name='最近计划执行状态')),
                ('last_run_message', models.TextField(blank=True, default='', verbose_name='最近计划执行摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '配置备份策略',
                'verbose_name_plural': '配置备份策略',
                'db_table': 'ops_config_backup_policy',
            },
        ),
    ]
