import { useMemo } from 'react';

export function useAppScreenProps({
  datacenters,
  racks,
  rackDevices,
  ips,
  loginLogs,
  residentStaff,
  residentSearchSeed,
  consumeResidentSearchSeed,
  changeRequestSearchSeed,
  consumeChangeRequestSearchSeed,
  systemOverview,
  systemOverviewRefreshedAt,
  handleJumpToDc,
  navigateToShellTarget,
  setActiveTab,
  currentRole,
  currentUserDisplay,
  currentPermissions,
  sections,
  expandedSections,
  setExpandedSections,
  setSectionFormData,
  setIsSectionModalOpen,
  setSubnetFormData,
  setIsSubnetModalOpen,
  handleDeleteSection,
  subnets,
  selectedSubnetId,
  setSelectedSubnetId,
  handleDeleteSubnet,
  currentSubnet,
  ipViewMode,
  setIpViewMode,
  handleScanSubnet,
  isScanning,
  setIpFormData,
  setEditingIP,
  setIsIPModalOpen,
  searchQuery,
  setSearchQuery,
  tagFilter,
  setTagFilter,
  uniqueTags,
  handleDownloadTemplate,
  handleImportClick,
  isImporting,
  handleExport,
  filteredIPs,
  optionLists,
  handleDeleteIP,
  handlePoolIPClick,
  activeLocation,
  setActiveLocation,
  setCurrentDcForm,
  setIsDcModalOpen,
  handleDeleteDatacenter,
  dcimViewMode,
  setDcimViewMode,
  elevationLayout,
  setElevationLayout,
  handleExportExcel,
  handleExportHtml,
  handleExportImage,
  setCurrentRackForm,
  setIsRackModalOpen,
  datacenterPowerStats,
  currentRacks,
  getRackCalculatedPower,
  selectedRack,
  setSelectedRack,
  handleDeleteRack,
  setEditingDevice,
  handleZoomIn,
  handleZoomOut,
  handleZoomReset,
  elevationScrollRef,
  elevationContentRef,
  handleElevationMouseDown,
  handleElevationMouseLeave,
  handleElevationMouseUp,
  handleElevationMouseMove,
  viewState,
  refreshData,
  auditLogs,
  blocklist,
  setIsBlockModalOpen,
  handleUnblockIP,
  backups,
  backupSummary,
  handleManualBackup,
  handleDownloadBackup,
  users,
  roleDefinitions,
  currentUsername,
  handleOpenCreateUser,
  handleOpenEditUser,
  setResetTarget,
  setIsResetModalOpen,
  handleToggleUserActive,
  handleUnlockUser,
  handleDeleteUser,
}) {
  return useMemo(
    () => ({
      dashboardProps: {
        datacenters,
        racks,
        rackDevices,
        ips,
        logs: loginLogs,
        residentStaff,
        overview: systemOverview,
        lastRefreshedAt: systemOverviewRefreshedAt,
        onJumpToDc: (dcId) => handleJumpToDc(dcId, setActiveTab),
        onNavigate: navigateToShellTarget,
        currentRole,
        currentUserDisplay,
        currentPermissions,
      },
      ipamProps: {
        sections,
        expandedSections,
        setExpandedSections,
        setSectionFormData,
        setIsSectionModalOpen,
        setSubnetFormData,
        setIsSubnetModalOpen,
        handleDeleteSection,
        subnets,
        selectedSubnetId,
        setSelectedSubnetId,
        handleDeleteSubnet,
        currentSubnet,
        ipViewMode,
        setIpViewMode,
        handleScanSubnet,
        isScanning,
        setIpFormData,
        setEditingIP,
        setIsIPModalOpen,
        searchQuery,
        setSearchQuery,
        tagFilter,
        setTagFilter,
        uniqueTags,
        handleDownloadTemplate,
        handleImportClick,
        isImporting,
        handleExport,
        filteredIPs,
        optionLists,
        handleDeleteIP,
        handlePoolIPClick,
      },
      dcimProps: {
        datacenters,
        activeLocation,
        setActiveLocation,
        setCurrentDcForm,
        setIsDcModalOpen,
        handleDeleteDatacenter,
        dcimViewMode,
        setDcimViewMode,
        elevationLayout,
        setElevationLayout,
        handleDownloadTemplate,
        handleImportClick,
        isImporting,
        handleExportExcel,
        handleExportHtml,
        handleExportImage,
        setCurrentRackForm,
        setIsRackModalOpen,
        datacenterPowerStats,
        currentRacks,
        getRackCalculatedPower,
        selectedRack,
        setSelectedRack,
        handleDeleteRack,
        setEditingDevice,
        handleZoomIn,
        handleZoomOut,
        handleZoomReset,
        elevationScrollRef,
        elevationContentRef,
        handleElevationMouseDown,
        handleElevationMouseLeave,
        handleElevationMouseUp,
        handleElevationMouseMove,
        viewState,
        rackDevices,
      },
      residentProps: {
        residentStaff,
        onRefresh: refreshData,
        initialFilters: residentSearchSeed,
        onConsumeInitialFilters: consumeResidentSearchSeed,
      },
      changesProps: {
        initialRequestId: changeRequestSearchSeed,
        onConsumeInitialRequestId: consumeChangeRequestSearchSeed,
      },
      securityProps: {
        loginLogs,
        auditLogs,
        blocklist,
        onOpenBlockModal: () => setIsBlockModalOpen(true),
        onUnblock: handleUnblockIP,
      },
      backupProps: {
        backups,
        summary: backupSummary,
        onManualBackup: handleManualBackup,
        onDownloadBackup: handleDownloadBackup,
        onRefresh: refreshData,
      },
      usersProps: {
        users,
        roleDefinitions,
        currentUsername,
        onCreateUser: handleOpenCreateUser,
        onOpenEdit: handleOpenEditUser,
        onOpenReset: (user) => {
          setResetTarget({ ...user, must_change_password: true });
          setIsResetModalOpen(true);
        },
        onToggleActive: handleToggleUserActive,
        onUnlock: handleUnlockUser,
        onDeleteUser: handleDeleteUser,
      },
    }),
    [
      activeLocation,
      auditLogs,
      backups,
      backupSummary,
      blocklist,
      currentRacks,
      currentSubnet,
      currentUsername,
      datacenterPowerStats,
      datacenters,
      dcimViewMode,
      elevationLayout,
      expandedSections,
      filteredIPs,
      getRackCalculatedPower,
      handleDeleteDatacenter,
      handleDeleteIP,
      handleDeleteRack,
      handleDeleteSection,
      handleDeleteSubnet,
      handleDownloadBackup,
      handleDownloadTemplate,
      handleElevationMouseDown,
      handleElevationMouseLeave,
      handleElevationMouseMove,
      handleElevationMouseUp,
      handleExport,
      handleExportExcel,
      handleExportHtml,
      handleExportImage,
      handleImportClick,
      handleJumpToDc,
      navigateToShellTarget,
      handleManualBackup,
      handleOpenCreateUser,
      handleOpenEditUser,
      handlePoolIPClick,
      handleScanSubnet,
      handleToggleUserActive,
      handleUnblockIP,
      handleUnlockUser,
      handleDeleteUser,
      handleZoomIn,
      handleZoomOut,
      handleZoomReset,
      ipViewMode,
      ips,
      isImporting,
      isScanning,
      loginLogs,
      optionLists,
      rackDevices,
      racks,
      refreshData,
      residentStaff,
      residentSearchSeed,
      consumeResidentSearchSeed,
      changeRequestSearchSeed,
      consumeChangeRequestSearchSeed,
      roleDefinitions,
      searchQuery,
      sections,
      selectedRack,
      selectedSubnetId,
      setActiveTab,
      setActiveLocation,
      setCurrentDcForm,
      setCurrentRackForm,
      setEditingIP,
      setExpandedSections,
      setIpFormData,
      setIpViewMode,
      setIsDcModalOpen,
      setIsIPModalOpen,
      setIsRackModalOpen,
      setIsResetModalOpen,
      setIsSectionModalOpen,
      setIsSubnetModalOpen,
      setIsBlockModalOpen,
      setResetTarget,
      setSearchQuery,
      setSelectedRack,
      setSelectedSubnetId,
      setSectionFormData,
      setSubnetFormData,
      setTagFilter,
      subnets,
      systemOverview,
      systemOverviewRefreshedAt,
      currentRole,
      currentUserDisplay,
      currentPermissions,
      tagFilter,
      uniqueTags,
      users,
      viewState,
      elevationScrollRef,
      elevationContentRef,
    ]
  );
}
